apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base
labels:
  - pairs:
      tracey.ai/deployment-profile: production
images:
  - name: tracey-api
    newName: ghcr.io/amandeepsingh29/tracey-api
    newTag: 0.1.0
  - name: tracey-executor
    newName: ghcr.io/amandeepsingh29/tracey-executor
    newTag: 0.1.0
  - name: tracey-worker
    newName: ghcr.io/amandeepsingh29/tracey-worker
    newTag: 0.1.0
  - name: tracey-ui
    newName: ghcr.io/amandeepsingh29/tracey-ui
    newTag: 0.1.0
