"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarClock, Check, Download, GitCompareArrows, GitPullRequestArrow, MessageCircleQuestion, Pencil, Play, ShieldAlert, X } from "lucide-react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { Button, EmptyState, ErrorState, JsonView, LoadingState, Modal, PageHeader, Panel, SegmentedControl, StatusChip } from "../components/ui";
import { api } from "../lib/api";
import { dateTime, relativeTime, titleCase } from "../lib/format";

const activeStatuses = ["awaiting_approval", "approved", "approved_for_auto_execution", "executing", "verifying", "reverting"];

export function ChangesPage() {
  const router = useRouter();
  const params = useSearchParams();
  const [status, setStatus] = useState(params.get("status") ?? "all");
  const query = useQuery({ queryKey: ["actions"], queryFn: () => api.actions(), refetchInterval: 10_000 });
  const actions = useMemo(() => (query.data?.actions ?? []).filter((action) => status === "all" || (status === "active" ? activeStatuses.includes(action.status) : action.status === status)), [query.data, status]);
  return <div className="page"><PageHeader eyebrow="CHANGE CONTROL" title="Changes and recovery" description="Review exact infrastructure proposals, approve immutable actions, and follow execution, verification, and rollback from one durable timeline." />
    <div className="change-summary"><div><strong>{query.data?.actions.filter(({ status: value }) => value === "awaiting_approval").length ?? 0}</strong><span>Awaiting approval</span></div><div><strong>{query.data?.actions.filter(({ status: value }) => ["executing", "verifying", "reverting"].includes(value)).length ?? 0}</strong><span>In progress</span></div><div><strong>{query.data?.actions.filter(({ status: value }) => ["succeeded", "reverted"].includes(value)).length ?? 0}</strong><span>Verified outcomes</span></div></div>
    <div className="filter-bar"><SegmentedControl label="Change status" value={status} onChange={setStatus} options={[{ value: "all", label: "All" }, { value: "active", label: "Active" }, { value: "awaiting_approval", label: "Needs approval" }, { value: "succeeded", label: "Succeeded" }, { value: "failed", label: "Failed" }]} /></div>
    {query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} onRetry={() => void query.refetch()} /> : actions.length === 0 ? <EmptyState icon={GitPullRequestArrow} title="No changes in this view" description="Evidence-backed remediation proposals will appear here with risk, scope, verification, and rollback information." /> : <div className="change-list">{actions.map((action) => <button key={action.proposalId} onClick={() => router.push(`/changes/${action.proposalId}`)}><div className="change-kind"><GitCompareArrows /></div><div className="change-main"><header><strong>{action.remediationPlan?.summary ?? titleCase(action.actionType)}</strong><StatusChip value={action.status} /></header><p>{action.reason}</p><footer><code>{action.target}</code><span>{titleCase(action.risk)} risk</span><span>{relativeTime(action.createdAt)}</span></footer></div></button>)}</div>}
  </div>;
}

export function ChangeDetailPage() {
  const params = useParams<{ proposalId: string }>();
  const proposalId = params.proposalId ?? "";
  const router = useRouter();
  const client = useQueryClient();
  const [confirm, setConfirm] = useState<"approve" | "reject" | "execute" | null>(null);
  const [revisionOpen, setRevisionOpen] = useState(false);
  const [scheduleOpen, setScheduleOpen] = useState(false);
  const query = useQuery({ queryKey: ["action", proposalId], queryFn: () => api.action(proposalId), refetchInterval: (result) => activeStatuses.includes(result.state.data?.action.status ?? "") ? 2_000 : false });
  const decision = useMutation({ mutationFn: (value: "approved" | "rejected") => api.decideAction(proposalId, value), onSuccess: async () => { setConfirm(null); await Promise.all([client.invalidateQueries({ queryKey: ["action", proposalId] }), client.invalidateQueries({ queryKey: ["actions"] })]); } });
  const execute = useMutation({ mutationFn: () => api.executeAction(proposalId), onSuccess: async () => { setConfirm(null); await Promise.all([client.invalidateQueries({ queryKey: ["action", proposalId] }), client.invalidateQueries({ queryKey: ["actions"] })]); } });
  const preview = useQuery({ queryKey: ["action-preview", proposalId], queryFn: () => api.previewAction(proposalId), retry: false });
  const revision = useMutation({ mutationFn: (reason: string) => api.requestActionRevision(proposalId, reason), onSuccess: async () => { setRevisionOpen(false); await client.invalidateQueries({ queryKey: ["action", proposalId] }); } });
  const schedule = useMutation({ mutationFn: (scheduledFor: string) => api.scheduleAction(proposalId, scheduledFor), onSuccess: async () => { setScheduleOpen(false); await Promise.all([client.invalidateQueries({ queryKey: ["action", proposalId] }), client.invalidateQueries({ queryKey: ["actions"] })]); } });
  if (query.isLoading) return <div className="page"><LoadingState /></div>;
  if (query.error || !query.data) return <div className="page"><ErrorState error={query.error ?? new Error("Change not found")} /></div>;
  const { action, events } = query.data;
  const plan = action.remediationPlan;
  const verification = action.verificationResult as { verified?: boolean; workloadReady?: boolean; rollout?: Record<string, unknown>; observability?: { baseline?: { errorRate?: number; p95LatencyMs?: number }; current?: { errorRate?: number; p95LatencyMs?: number }; errorRateIncrease?: number; latencyIncreasePercent?: number }; reason?: string; reasons?: string[] } | undefined;
  const exportCommand = () => { const content = JSON.stringify(plan?.action ?? { actionType: action.actionType, target: action.target, parameters: action.parameters }, null, 2); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "application/json" })); link.download = `tracey-change-${proposalId}.json`; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="page change-detail"><button className="back-link" onClick={() => router.push("/changes")}><ArrowLeft size={15} />All changes</button><PageHeader eyebrow="IMMUTABLE CHANGE PROPOSAL" title={plan?.summary ?? titleCase(action.actionType)} description={action.reason} actions={<><Button variant="ghost" onClick={() => router.push(`/investigations/${action.sessionId}?prompt=${encodeURIComponent(`Explain change proposal ${action.proposalId}, its evidence, risk, blast radius, and rollback plan.`)}`)}><MessageCircleQuestion size={16} />Explain</Button><Button variant="secondary" onClick={exportCommand}><Download size={16} />Export action</Button>{action.status === "awaiting_approval" && <><Button variant="secondary" onClick={() => setRevisionOpen(true)}><Pencil size={16} />Request revision</Button><Button variant="danger" onClick={() => setConfirm("reject")}><X size={16} />Reject</Button><Button onClick={() => setConfirm("approve")}><Check size={16} />Approve</Button></>}{action.status === "approved" && <><Button variant="secondary" onClick={() => setScheduleOpen(true)}><CalendarClock size={16} />Schedule</Button><Button onClick={() => setConfirm("execute")}><Play size={16} />Execute and verify</Button></>}</>} />
    <div className="change-hero"><div><span>Current state</span><StatusChip value={action.status} /></div><div><span>Target</span><code>{action.target}</code></div><div><span>Risk</span><StatusChip value={action.risk} /></div><div><span>Requested by</span><strong>{action.proposedBy}</strong></div>{action.approvedBy && <div><span>Approved by</span><strong>{action.approvedBy}</strong></div>}{action.scheduledFor && <div><span>Scheduled</span><strong>{dateTime(action.scheduledFor)}</strong><small>{action.scheduledBy}</small></div>}</div>
    <div className="two-column"><Panel title="Why this change" subtitle="Tracey’s recommendation based on the linked investigation."><div className="prose-block"><p>{plan?.reason ?? action.reason}</p>{plan && <><h3>Expected impact</h3><p>{plan.expectedImpact}</p><div className="fact-grid"><div><span>Confidence</span><strong>{Math.round(plan.confidence * 100)}%</strong></div><div><span>Reversible</span><strong>{plan.reversible ? "Yes" : "No"}</strong></div><div><span>Workloads</span><strong>{plan.blastRadius.workloads}</strong></div><div><span>Unavailable replicas</span><strong>{plan.blastRadius.estimatedUnavailableReplicas}</strong></div></div></>}</div></Panel><Panel title="Policy decision" subtitle="Deterministic controls applied before execution."><div className="policy-decision"><ShieldAlert /><StatusChip value={action.policyDecision?.decision ?? "not evaluated"} /><p>{action.policyDecision?.reasons?.join(" · ") ?? "No policy evaluation is attached."}</p>{action.policyDecision?.evaluatedAt && <span>{dateTime(action.policyDecision.evaluatedAt)}</span>}</div></Panel></div>
    <Panel title="Exact change preview" subtitle="The before-state is read live without mutation. The approved object is immutable; revisions require a new confirmation.">{preview.isLoading ? <LoadingState label="Capturing live before-state" /> : <div className="diff-grid"><div><header>Before {preview.data?.capturedAt && `· ${dateTime(preview.data.capturedAt)}`}</header><pre>{JSON.stringify(action.preActionSnapshot ?? preview.data?.before ?? { unavailable: preview.error instanceof Error ? preview.error.message : "No before-state returned" }, null, 2)}</pre></div><div><header>Proposed action</header><pre>{JSON.stringify(preview.data?.proposed ?? plan?.action ?? action.parameters, null, 2)}</pre></div></div>}</Panel>
    {plan && <div className="two-column"><Panel title="Verification plan"><JsonView value={plan.verification} label="Verification thresholds" /></Panel><Panel title="Rollback plan">{plan.rollback ? <JsonView value={plan.rollback} label={plan.rollback.automatic ? "Automatic recovery" : "Operator recovery"} /> : <EmptyState title="No automatic rollback" description="If verification fails, Tracey will stop and require an operator-authored recovery proposal." action={<Button variant="secondary" onClick={() => router.push(`/investigations/${action.sessionId}?prompt=${encodeURIComponent(`Prepare a safe manual recovery proposal for change ${action.proposalId}. Use current evidence and require approval.`)}`)}>Prepare manual recovery</Button>} />}</Panel></div>}
    <Panel title="Execution timeline" subtitle="Every transition is persisted with its actor and timestamp."><div className="timeline">{events.map((event) => <div key={event.eventId}><span className="timeline-marker" /><div><header><strong>{titleCase(event.toStatus)}</strong><time>{dateTime(event.createdAt)}</time></header><p>{event.fromStatus ? `Transitioned from ${titleCase(event.fromStatus)}` : "Action created"} · {event.actor}</p>{Object.keys(event.details).length > 0 && <JsonView value={event.details} />}</div></div>)}</div></Panel>
    {(action.executionResult || action.verificationResult || action.rollbackResult) && <Panel title="Observed outcome" subtitle="Semantic readiness and health comparisons are backed by the durable executor receipts below."><div className="outcome-summary"><div><span>Executor</span><strong>{action.executionResult ? "Accepted" : "Pending"}</strong></div><div><span>Kubernetes readiness</span><strong>{verification?.workloadReady === undefined ? "Not reported" : verification.workloadReady ? "Ready" : "Not ready"}</strong></div><div><span>Health verification</span><strong>{verification?.verified === undefined ? "Pending" : verification.verified ? "Passed" : "Failed"}</strong></div><div><span>Recovery</span><strong>{action.rollbackResult ? action.status === "reverted" ? "Verified" : "Attempted" : plan?.rollback?.automatic ? "Available" : "Manual"}</strong></div></div>{verification?.observability && <div className="health-comparison"><div><span>Before error rate</span><strong>{((verification.observability.baseline?.errorRate ?? 0) * 100).toFixed(2)}%</strong></div><div><span>After error rate</span><strong>{((verification.observability.current?.errorRate ?? 0) * 100).toFixed(2)}%</strong></div><div><span>Before P95</span><strong>{verification.observability.baseline?.p95LatencyMs ?? 0} ms</strong></div><div><span>After P95</span><strong>{verification.observability.current?.p95LatencyMs ?? 0} ms</strong></div></div>}{(verification?.reason || verification?.reasons?.length) && <div className="error-state"><ShieldAlert /><div><h3>Verification explanation</h3><p>{verification.reason ?? verification.reasons?.join(" · ")}</p></div></div>}<div className="outcome-grid">{action.executionResult && <JsonView value={action.executionResult} label="Executor receipt" />}{action.verificationResult && <JsonView value={action.verificationResult} label="Verification result" />}{action.rollbackResult && <JsonView value={action.rollbackResult} label="Recovery result" />}</div></Panel>}
    <Modal open={confirm !== null} onClose={() => setConfirm(null)} title={confirm === "approve" ? "Approve this exact change?" : confirm === "reject" ? "Reject this proposal?" : "Execute the approved change?"} description={confirm === "execute" ? "Tracey will send this immutable action to the authenticated executor, monitor readiness, and verify the outcome." : "This decision is recorded in the durable action timeline."}><div className="confirmation-body"><div className="confirmation-target"><span>Target</span><code>{action.target}</code></div><p>{plan?.summary ?? action.reason}</p>{(decision.error || execute.error) && <p className="form-error">{(decision.error ?? execute.error)?.message}</p>}<footer className="modal-actions"><Button variant="secondary" onClick={() => setConfirm(null)}>Cancel</Button>{confirm === "approve" && <Button disabled={decision.isPending} onClick={() => decision.mutate("approved")}>Confirm approval</Button>}{confirm === "reject" && <Button variant="danger" disabled={decision.isPending} onClick={() => decision.mutate("rejected")}>Confirm rejection</Button>}{confirm === "execute" && <Button disabled={execute.isPending} onClick={() => execute.mutate()}>Execute now</Button>}</footer></div></Modal>
    <Modal open={revisionOpen} onClose={() => setRevisionOpen(false)} title="Request a new revision" description="The current proposal remains immutable. This request is recorded in the timeline for Tracey or an operator to prepare a new proposal."><form className="form-stack" onSubmit={(event) => { event.preventDefault(); revision.mutate(String(new FormData(event.currentTarget).get("reason"))); }}><label className="field">Revision requirements<textarea name="reason" rows={5} minLength={10} required placeholder="Reduce blast radius, change the namespace scope, or adjust verification…" /></label>{revision.error && <p className="form-error">{revision.error.message}</p>}<div className="modal-actions"><Button variant="secondary" type="button" onClick={() => setRevisionOpen(false)}>Cancel</Button><Button disabled={revision.isPending}>Record revision request</Button></div></form></Modal>
    <Modal open={scheduleOpen} onClose={() => setScheduleOpen(false)} title="Schedule approved execution" description="A distributed Tracey worker will execute this same immutable proposal at the selected time. Status and verification remain visible here."><form className="form-stack" onSubmit={(event) => { event.preventDefault(); schedule.mutate(new Date(String(new FormData(event.currentTarget).get("scheduledFor"))).toISOString()); }}><label className="field">Execution time<input name="scheduledFor" type="datetime-local" min={new Date(Date.now() + 60_000).toISOString().slice(0, 16)} required /></label>{schedule.error && <p className="form-error">{schedule.error.message}</p>}<div className="modal-actions"><Button variant="secondary" type="button" onClick={() => setScheduleOpen(false)}>Cancel</Button><Button disabled={schedule.isPending}>Schedule execution</Button></div></form></Modal>
  </div>;
}
