"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Bell, Cable, Check, Eye, EyeOff, RefreshCw, Save, ShieldCheck, Trash2, TriangleAlert } from "lucide-react";
import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { Button, EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader, Panel, StatusChip } from "../components/ui";
import { api } from "../lib/api";
import { dateTime, relativeTime, titleCase } from "../lib/format";
import type { AutonomyPolicy, Connector, Notification } from "../types";

const preferenceOptions = [
  { key: "incidents", label: "Incidents" }, { key: "approvals", label: "Pending approvals" },
  { key: "failures", label: "Execution failures" }, { key: "recoveries", label: "Recoveries and rollbacks" },
  { key: "connectorProblems", label: "Connector problems" }, { key: "externalDelivery", label: "External delivery" },
];

const connectorCopy: Record<Connector["id"], { description: string; permissions: string[] }> = {
  signoz: { description: "Query traces, logs, metrics, and recovery evidence from your SigNoz workspace.", permissions: ["Read-only query API", "OTLP ingestion for telemetry producers"] },
  kubernetes: { description: "Inspect workloads and execute approved, typed remediation through scoped identities.", permissions: ["Read workload state", "Patch only allowed workloads after approval"] },
  codex: { description: "Normalize Codex desktop and CLI conversations, tools, latency, and token telemetry.", permissions: ["OTLP export from Codex", "Optional local session access for developer execution graphs"] },
  "claude-code": { description: "Observe Claude Code interactions through native OpenTelemetry export.", permissions: ["OTLP export from Claude Code", "No filesystem access"] },
  "generic-otel": { description: "Connect any custom agent that emits Tracey’s framework-neutral run contract.", permissions: ["OTLP ingestion", "Service metadata only"] },
  mcp: { description: "Expose bounded Tracey investigation tools or observe an allowlisted external MCP server.", permissions: ["Explicit tool allowlist", "Authenticated MCP transport"] },
};

export function ConnectorsPage() {
  const client = useQueryClient();
  const [selected, setSelected] = useState<Connector | null>(null);
  const [tested, setTested] = useState<string | null>(null);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const query = useQuery({ queryKey: ["connectors"], queryFn: api.connectors, refetchInterval: 30_000 });
  const configuration = (form: HTMLFormElement, connector: Connector): Record<string, unknown> => { const data = new FormData(form);
    if (connector.id === "signoz") return { apiUrl: String(data.get("apiUrl")), apiKey: String(data.get("apiKey")), otlpEndpoint: String(data.get("otlpEndpoint") || "") || undefined, ingestionKey: String(data.get("ingestionKey") || "") || undefined };
    if (connector.id === "kubernetes") return { investigatorEnabled: data.get("investigatorEnabled") === "on", executorEnabled: data.get("executorEnabled") === "on", allowedNamespaces: String(data.get("allowedNamespaces")).split(",").map((value) => value.trim()).filter(Boolean), allowedWorkloads: String(data.get("allowedWorkloads")).split(",").map((value) => value.trim()).filter(Boolean) };
    if (connector.id === "mcp") return { serverUrl: String(data.get("serverUrl")), bearerToken: String(data.get("bearerToken") || "") || undefined, allowedReadTools: String(data.get("allowedReadTools")).split(",").map((value) => value.trim()).filter(Boolean) };
    return { serviceName: String(data.get("serviceName")), environment: String(data.get("environment")) };
  };
  const test = useMutation({ mutationFn: ({ id, value }: { id: Connector["id"]; value: Record<string, unknown> }) => api.testConnector(id, value), onSuccess: (result) => setTested(`Connected as ${result.effectiveIdentity} at ${dateTime(result.checkedAt)}`) });
  const save = useMutation({ mutationFn: ({ id, value }: { id: Connector["id"]; value: Record<string, unknown> }) => api.configureConnector(id, value), onSuccess: async () => { setSelected(null); setTested(null); await client.invalidateQueries({ queryKey: ["connectors"] }); } });
  const state = useMutation({ mutationFn: ({ id, enabled }: { id: Connector["id"]; enabled: boolean }) => api.setConnectorEnabled(id, enabled), onSuccess: async () => client.invalidateQueries({ queryKey: ["connectors"] }) });
  const remove = useMutation({ mutationFn: (id: Connector["id"]) => api.deleteConnector(id), onSuccess: async () => { setSelected(null); setConfirmDelete(false); await client.invalidateQueries({ queryKey: ["connectors"] }); } });
  const submit = (event: FormEvent<HTMLFormElement>, mode: "test" | "save") => { event.preventDefault(); if (!selected) return; const value = configuration(event.currentTarget, selected); if (mode === "test") test.mutate({ id: selected.id, value }); else save.mutate({ id: selected.id, value }); };
  return <div className="page"><PageHeader eyebrow="INTEGRATION CONTROL PLANE" title="Connectors" description="Connect external observability, infrastructure, agent producers, and protocols without merging their code into Tracey." actions={<Button variant="secondary" onClick={() => void query.refetch()}><RefreshCw size={16} />Refresh health</Button>} />
    <div className="security-banner"><ShieldCheck /><div><strong>Credentials stay server-side</strong><p>Tracey’s browser receives connector state and capability metadata, never stored credential values.</p></div></div>
    {query.data && !query.data.secretStorageAvailable && <div className="error-state"><TriangleAlert /><div><h3>Secure connector storage is unavailable</h3><p>Configure PostgreSQL and the Tracey API bearer token or a dedicated connector encryption key.</p></div></div>}
    {query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} onRetry={() => void query.refetch()} /> : <div className="connector-grid">{query.data?.connectors.map((connector) => <article className="connector-card" key={connector.id}><header><div className="connector-logo"><Cable /></div><StatusChip value={connector.state} /></header><h2>{connector.displayName}</h2><p>{connectorCopy[connector.id].description}</p><h3>Required access</h3><ul>{connectorCopy[connector.id].permissions.map((permission) => <li key={permission}><Check size={13} />{permission}</li>)}</ul><div className="connector-capabilities">{connector.capabilities.slice(0, 4).map((capability) => <span key={capability}>{titleCase(capability)}</span>)}</div>{connector.configuration?.lastCheckedAt && <small>Last checked {relativeTime(connector.configuration.lastCheckedAt)} · {connector.configuration.effectiveIdentity}</small>}<footer><span>{connector.statusReason}</span>{connector.configuration?.configured && <Button variant="ghost" disabled={state.isPending} onClick={() => state.mutate({ id: connector.id, enabled: !connector.configuration!.enabled })}>{connector.configuration.enabled ? "Disable" : "Enable"}</Button>}<Button variant={connector.state === "ready" ? "secondary" : "primary"} onClick={() => { setSelected(connector); setTested(null); }}>{connector.state === "ready" ? "Reconfigure" : "Set up"}</Button></footer></article>)}</div>}
    <Panel title="Product boundary" subtitle="Tracey connects to independently deployed systems through bounded adapters."><p className="prose-block">{query.data?.boundary}</p></Panel>
    <Modal open={selected !== null} onClose={() => setSelected(null)} title={`${selected?.configuration ? "Reconfigure" : "Connect"} ${selected?.displayName ?? "connector"}`} description="Test endpoint access and effective permissions before saving. Stored secret values are never returned to this form.">{selected && <form className="form-stack" onSubmit={(event) => submit(event, "save")}>
      <ConnectorFields connector={selected} />
      <div className="connector-warning"><TriangleAlert size={15} /><span>{connectorCopy[selected.id].permissions.join(" · ")}</span></div>
      {tested && <p className="connection-success"><Check size={15} />{tested}</p>}{(test.error || save.error) && <p className="form-error">{(test.error ?? save.error)?.message}</p>}
      <div className="modal-actions">{selected.configuration && <Button variant="danger" type="button" onClick={() => setConfirmDelete(true)}>Delete</Button>}<Button variant="secondary" type="button" disabled={test.isPending} onClick={(event) => { const form = event.currentTarget.closest("form"); if (form) test.mutate({ id: selected.id, value: configuration(form, selected) }); }}>Test connection</Button><Button disabled={save.isPending}>Save and connect</Button></div>
    </form>}</Modal>
    <Modal open={confirmDelete} onClose={() => setConfirmDelete(false)} title="Delete connector configuration?" description="Tracey will remove stored settings and encrypted credentials. External systems are not modified."><div className="confirmation-body"><p>{selected?.displayName}</p><div className="modal-actions"><Button variant="secondary" onClick={() => setConfirmDelete(false)}>Cancel</Button><Button variant="danger" disabled={remove.isPending} onClick={() => selected && remove.mutate(selected.id)}>Delete configuration</Button></div></div></Modal>
  </div>;
}

function ConnectorFields({ connector }: { connector: Connector }) {
  const values = connector.configuration?.publicConfig ?? {};
  if (connector.id === "signoz") return <div className="form-grid"><Field label="SigNoz instance URL" hint="Example: https://your-workspace.signoz.cloud"><input name="apiUrl" type="url" defaultValue={String(values.apiUrl ?? "")} required /></Field><Field label="Query API key" hint={connector.configuration?.secretNames.includes("apiKey") ? "Stored securely; enter again to rotate" : "Read-only query permissions required"}><input name="apiKey" type="password" autoComplete="new-password" required /></Field><Field label="OTLP endpoint"><input name="otlpEndpoint" type="url" defaultValue={String(values.otlpEndpoint ?? "")} /></Field><Field label="Ingestion key"><input name="ingestionKey" type="password" autoComplete="new-password" /></Field></div>;
  if (connector.id === "kubernetes") return <div className="form-stack connector-inline"><label className="toggle"><input name="investigatorEnabled" type="checkbox" defaultChecked={values.investigatorEnabled !== false} />Read-only investigation</label><label className="toggle"><input name="executorEnabled" type="checkbox" defaultChecked={Boolean(values.executorEnabled)} />Approved mutation executor</label><Field label="Allowed namespaces" hint="Comma-separated; wildcards are not accepted"><input name="allowedNamespaces" defaultValue={Array.isArray(values.allowedNamespaces) ? values.allowedNamespaces.join(", ") : "production"} required /></Field><Field label="Allowed workloads"><input name="allowedWorkloads" defaultValue={Array.isArray(values.allowedWorkloads) ? values.allowedWorkloads.join(", ") : ""} /></Field></div>;
  if (connector.id === "mcp") return <div className="form-grid"><Field label="MCP server URL"><input name="serverUrl" type="url" defaultValue={String(values.serverUrl ?? "")} required /></Field><Field label="Bearer token"><input name="bearerToken" type="password" autoComplete="new-password" /></Field><Field label="Allowed read tools"><input name="allowedReadTools" defaultValue={Array.isArray(values.allowedReadTools) ? values.allowedReadTools.join(", ") : ""} /></Field></div>;
  return <div className="form-grid"><Field label="Service name"><input name="serviceName" defaultValue={String(values.serviceName ?? (connector.id === "codex" ? "codex-app-server" : ""))} required /></Field><Field label="Environment"><input name="environment" defaultValue={String(values.environment ?? "production")} required /></Field></div>;
}

const defaultPolicy: AutonomyPolicy = { mode: "approval", environments: ["production", "development"], namespaces: ["*"], workloads: ["*"], allowedActions: ["restart_pod", "restart_workload", "rollback_deployment", "scale_deployment", "update_resource_limits", "update_hpa", "retry_job", "suspend_cronjob", "resume_cronjob", "apply_config_patch", "restore_previous_config", "apply_kubernetes_resource", "patch_kubernetes_resource", "delete_kubernetes_resource"], automaticActions: [], prohibitedActions: ["read_secrets", "delete_namespace", "delete_database", "arbitrary_shell"], minimumConfidence: .8, maximumAutomaticRisk: "low", maxReplicas: 20, maxAffectedWorkloads: 5, maxUnavailableReplicas: 1, maxConcurrentActions: 2, cooldownMinutes: 5 };
const modeCopy: Record<AutonomyPolicy["mode"], string> = { observe: "Read evidence only; never propose or execute.", recommend: "Investigate and propose changes; execution remains external.", approval: "Every mutation requires an explicit human approval.", guarded_autopilot: "Low-risk, allowlisted changes may run automatically inside strict scopes.", full_autopilot: "Broad autonomy within policy scopes. Use only in controlled environments." };

export function PoliciesPage() {
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["policies"], queryFn: api.policies });
  const history = useQuery({ queryKey: ["policy-history", "global", "default"], queryFn: () => api.policyHistory("global", "default"), retry: false });
  const [draft, setDraft] = useState<AutonomyPolicy | null>(null);
  const [pendingMode, setPendingMode] = useState<AutonomyPolicy["mode"] | null>(null);
  const active = draft ?? query.data?.policies.find((item) => item.scopeType === "global")?.policy ?? defaultPolicy;
  const save = useMutation({ mutationFn: () => api.savePolicy("global", "default", active), onSuccess: async () => { setDraft(null); await Promise.all([client.invalidateQueries({ queryKey: ["policies"] }), client.invalidateQueries({ queryKey: ["policy-history"] })]); } });
  const update = <K extends keyof AutonomyPolicy>(key: K, value: AutonomyPolicy[K]) => setDraft({ ...active, [key]: value });
  useEffect(() => { const saved = window.localStorage.getItem("tracey.policy-draft"); if (saved) { try { setDraft(JSON.parse(saved) as AutonomyPolicy); } catch { window.localStorage.removeItem("tracey.policy-draft"); } } }, []);
  useEffect(() => { if (draft) window.localStorage.setItem("tracey.policy-draft", JSON.stringify(draft)); else window.localStorage.removeItem("tracey.policy-draft"); }, [draft]);
  return <div className="page"><PageHeader eyebrow="DETERMINISTIC SAFETY" title="Policies and autonomy" description="Choose how Tracey moves from evidence to action. New installations remain approval-first by default." actions={<Button disabled={!draft || save.isPending} onClick={() => save.mutate()}><Save size={16} />Save policy</Button>} />
    {query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} /> : <><Panel title="Policy templates" subtitle="Start with conservative environment defaults, then preview changes before saving."><div className="template-row"><Button variant="secondary" onClick={() => setDraft({ ...defaultPolicy, environments: ["production"], mode: "approval" })}>Production approval</Button><Button variant="secondary" onClick={() => setPendingMode("guarded_autopilot")}>Development guarded</Button><Button variant="secondary" onClick={() => setDraft({ ...defaultPolicy, environments: ["*"], mode: "observe", allowedActions: [], automaticActions: [] })}>Observe only</Button></div></Panel><div className="mode-grid">{(Object.keys(modeCopy) as AutonomyPolicy["mode"][]).map((mode) => <button key={mode} className={active.mode === mode ? "active" : ""} onClick={() => mode === "guarded_autopilot" || mode === "full_autopilot" ? setPendingMode(mode) : update("mode", mode)}><StatusChip value={mode === "approval" ? "recommended" : mode} /><strong>{titleCase(mode)}</strong><p>{modeCopy[mode]}</p>{mode === "full_autopilot" && <span className="danger-copy"><TriangleAlert size={13} />High consequence</span>}</button>)}</div>
      <div className="two-column"><Panel title="Scope" subtitle="Where this policy may apply."><div className="policy-form"><label>Environments<input value={active.environments.join(", ")} onChange={(event) => update("environments", event.target.value.split(",").map((value) => value.trim()).filter(Boolean))} /></label><label>Namespaces<input value={active.namespaces.join(", ")} onChange={(event) => update("namespaces", event.target.value.split(",").map((value) => value.trim()).filter(Boolean))} /></label><label>Workloads<input value={active.workloads.join(", ")} onChange={(event) => update("workloads", event.target.value.split(",").map((value) => value.trim()).filter(Boolean))} /></label></div></Panel><Panel title="Guardrails" subtitle="Hard limits evaluated before execution."><details className="advanced-policy"><summary>Advanced execution limits</summary><div className="policy-form"><label>Minimum confidence<input type="number" min="0" max="1" step=".05" value={active.minimumConfidence} onChange={(event) => update("minimumConfidence", Number(event.target.value))} /></label><label>Maximum automatic risk<select value={active.maximumAutomaticRisk} onChange={(event) => update("maximumAutomaticRisk", event.target.value as AutonomyPolicy["maximumAutomaticRisk"])}>{["low", "medium", "high", "critical"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Concurrent actions<input type="number" min="1" value={active.maxConcurrentActions} onChange={(event) => update("maxConcurrentActions", Number(event.target.value))} /></label></div></details></Panel></div>
      {draft && <Panel title="Unsaved policy effect preview" subtitle="This preview is derived from the exact draft that will be submitted."><div className="policy-preview"><div><span>Mode</span><strong>{titleCase(active.mode)}</strong></div><div><span>Automatic actions</span><strong>{active.automaticActions.length || "None"}</strong></div><div><span>Max risk</span><strong>{titleCase(active.maximumAutomaticRisk)}</strong></div><div><span>Scopes</span><strong>{active.environments.length} env · {active.namespaces.length} namespace</strong></div></div></Panel>}
      <Panel title="Immutable version history" subtitle="Every saved policy version is append-only and records its actor.">{history.data?.versions.length ? <div className="table-wrap"><table><thead><tr><th>Scope</th><th>Mode</th><th>Version</th><th>Actor</th><th>Created</th></tr></thead><tbody>{history.data.versions.map((policy) => <tr key={`${policy.policyId}-${policy.version}`}><td><strong>{policy.scopeType}</strong> / {policy.scopeId}</td><td><StatusChip value={policy.policy.mode} /></td><td>v{policy.version}</td><td>{policy.actor}</td><td>{dateTime(policy.createdAt)}</td></tr>)}</tbody></table></div> : <EmptyState icon={ShieldCheck} title="Approval mode is the safe default" description="Save the first global policy to create its immutable version history." />}</Panel></>}
    <Modal open={pendingMode !== null} onClose={() => setPendingMode(null)} title={`Enable ${titleCase(pendingMode ?? "autopilot")}?`} description="Autopilot can mutate connected infrastructure without waiting for each approval. Deterministic scopes and risk limits still apply."><div className="confirmation-body"><div className="connector-warning"><TriangleAlert /><span>Review namespaces, workloads, automatic action types, blast radius, and recovery limits before saving.</span></div><div className="modal-actions"><Button variant="secondary" onClick={() => setPendingMode(null)}>Cancel</Button><Button variant="danger" onClick={() => { if (pendingMode) setDraft({ ...active, mode: pendingMode, ...(pendingMode === "guarded_autopilot" ? { environments: ["development"], automaticActions: ["restart"], maximumAutomaticRisk: "low" as const } : {}) }); setPendingMode(null); }}>I understand, enable mode</Button></div></div></Modal>
  </div>;
}

export function NotificationsPage() {
  const client = useQueryClient();
  const [unread, setUnread] = useState(false);
  const [severity, setSeverity] = useState("all");
  const [category, setCategory] = useState("all");
  const [environment, setEnvironment] = useState("all");
  const query = useQuery({ queryKey: ["notifications", unread], queryFn: () => api.notifications(unread), refetchInterval: 15_000 });
  const mutate = useMutation({ mutationFn: ({ id, op }: { id: string; op: "read" | "archive" | "dismiss" }) => op === "read" ? api.markNotificationRead(id) : api.archiveNotification(id, op), onSuccess: async () => client.invalidateQueries({ queryKey: ["notifications"] }) });
  const all = useMutation({ mutationFn: api.markAllNotificationsRead, onSuccess: async () => client.invalidateQueries({ queryKey: ["notifications"] }) });
  const notifications = (query.data?.notifications ?? []).filter((item) => (severity === "all" || item.severity === severity) && (category === "all" || item.category === category) && (environment === "all" || item.environment === environment));
  const environments = [...new Set((query.data?.notifications ?? []).map((item) => item.environment).filter((value): value is string => Boolean(value)))];
  const source = (item: Notification) => item.sessionId ? `/investigations/${item.sessionId}` : item.correlationType === "trace" ? `/runs/${item.correlationId}` : "/agents";
  return <div className="page"><PageHeader eyebrow="IN-PRODUCT OPERATIONS" title="Notifications" description="A focused inbox for incidents, approvals, failures, recoveries, and connector health. External delivery remains optional." actions={<Button variant="secondary" disabled={all.isPending} onClick={() => all.mutate()}><Check size={16} />Mark all read</Button>} />
    <div className="filter-bar"><label className="toggle"><input type="checkbox" checked={unread} onChange={(event) => setUnread(event.target.checked)} />Unread only</label><select value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="all">All severities</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option></select><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{["incident", "approval", "failure", "recovery", "connector", "system"].map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select><select value={environment} onChange={(event) => setEnvironment(event.target.value)}><option value="all">All environments</option>{environments.map((value) => <option key={value}>{value}</option>)}</select></div>
    {query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} /> : notifications.length === 0 ? <EmptyState icon={Bell} title="Inbox clear" description="Operational events will appear here without requiring Slack, email, or PagerDuty." /> : <div className="notification-list">{notifications.map((item) => <article key={item.notificationId} className={item.readAt ? "read" : "unread"}><span className={`notification-icon severity-${item.severity}`}><Bell /></span><div><header><Link href={source(item)}>{item.title}</Link><StatusChip value={item.severity} /></header><p>{item.summary}</p><footer><span>{titleCase(item.category ?? "system")}</span>{item.environment && <span>{item.environment}</span>}<span>{titleCase(item.correlationType)}</span><span>{relativeTime(item.createdAt)}</span></footer></div><aside>{!item.readAt && <button onClick={() => mutate.mutate({ id: item.notificationId, op: "read" })} aria-label="Mark read"><Eye size={16} /></button>}<button onClick={() => mutate.mutate({ id: item.notificationId, op: "archive" })} aria-label="Archive"><Archive size={16} /></button><button onClick={() => mutate.mutate({ id: item.notificationId, op: "dismiss" })} aria-label="Dismiss"><Trash2 size={16} /></button></aside></article>)}</div>}
  </div>;
}

export function SettingsPage() {
  const health = useQuery({ queryKey: ["health"], queryFn: api.health });
  const preferences = useQuery({ queryKey: ["notification-preferences"], queryFn: api.notificationPreferences });
  const investigations = useQuery({ queryKey: ["investigations"], queryFn: api.investigations });
  const client = useQueryClient();
  const [clearOpen, setClearOpen] = useState(false);
  const [clearPhrase, setClearPhrase] = useState("");
  const save = useMutation({ mutationFn: api.saveNotificationPreferences, onSuccess: async () => client.invalidateQueries({ queryKey: ["notification-preferences"] }) });
  const clear = useMutation({
    mutationFn: api.clearInvestigations,
    onSuccess: async () => {
      setClearOpen(false);
      setClearPhrase("");
      await Promise.all([
        client.invalidateQueries({ queryKey: ["investigations"] }),
        client.invalidateQueries({ queryKey: ["messages"] }),
        client.invalidateQueries({ queryKey: ["actions"] }),
      ]);
    },
  });
  const values = preferences.data?.preferences ?? {};
  const investigationCount = investigations.data?.investigations.length ?? 0;
  const update = (key: string, value: boolean) => save.mutate({ ...values, [key]: value });
  return <div className="page"><PageHeader eyebrow="WORKSPACE" title="Settings" description="Review deployment boundaries, runtime health, privacy controls, and in-product notification preferences." />
    <div className="two-column"><Panel title="Runtime health">{health.isLoading ? <LoadingState /> : health.error ? <ErrorState error={health.error} /> : <div className="settings-list">{Object.entries(health.data?.integrations ?? {}).map(([name, state]) => <div key={name}><span>{titleCase(name)}</span><StatusChip value={state} /></div>)}</div>}</Panel><Panel title="Access boundary"><div className="settings-copy"><EyeOff /><h3>No browser credential access</h3><p>The Next.js server proxy injects Tracey API credentials. Local no-login mode should only bind to loopback or a private development network.</p><p>OIDC and multi-user roles remain an API boundary and can be enabled without redesigning these screens.</p></div></Panel></div>
    <Panel title="Notification preferences" subtitle="In-product delivery is primary; external providers are optional.">{preferences.isLoading ? <LoadingState /> : <div className="preference-list">{preferenceOptions.map(({ key, label }) => <label key={key}><span><strong>{label}</strong><small>{key === "externalDelivery" ? "Optional Slack, email, or PagerDuty adapters" : "Show in the Tracey operations inbox"}</small></span><input type="checkbox" checked={Boolean(values[key])} onChange={(event) => update(key, event.target.checked)} /></label>)}</div>}</Panel>
    <Panel title="Data management" subtitle="Remove tenant-scoped product history without changing connected infrastructure or external telemetry."><div className="settings-danger-zone"><div><Trash2 /><span><strong>Clear investigation history</strong><small>{investigations.isLoading ? "Counting investigations…" : investigationCount === 0 ? "No investigations are currently stored." : `${investigationCount} investigation${investigationCount === 1 ? "" : "s"} currently stored.`}</small></span></div><Button variant="danger" disabled={investigations.isLoading || investigationCount === 0} onClick={() => setClearOpen(true)}>Clear investigations</Button></div></Panel>
    <Modal open={clearOpen} onClose={() => { setClearOpen(false); setClearPhrase(""); }} title="Clear all investigation history?" description="This permanently deletes every investigation session, message, evidence reference, tool audit, and related change proposal for this Tracey workspace. Connected systems and external telemetry are not modified."><div className="confirmation-body"><div className="connector-warning"><TriangleAlert size={16} /><span>This action cannot be undone. Type CLEAR to confirm deletion of {investigationCount} investigation{investigationCount === 1 ? "" : "s"}.</span></div><label className="field">Confirmation<input autoFocus value={clearPhrase} onChange={(event) => setClearPhrase(event.target.value)} placeholder="Type CLEAR" autoComplete="off" /></label>{clear.error && <p className="form-error">{clear.error.message}</p>}<div className="modal-actions"><Button variant="secondary" onClick={() => { setClearOpen(false); setClearPhrase(""); }}>Cancel</Button><Button variant="danger" disabled={clear.isPending || clearPhrase !== "CLEAR"} onClick={() => clear.mutate()}>{clear.isPending ? "Clearing…" : "Permanently clear"}</Button></div></div></Modal>
  </div>;
}
